name: "Build and Deploy"

on:
  push:
    branches:
      - main

env:
  OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
  OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
  OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
  OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
  OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

jobs:
  ci:
    runs-on: ubuntu-22.04
    name: Build & Push Docker Image
    outputs:
      GITHUB_REF_NAME: ${{ steps.set-ref-name.outputs.GITHUB_REF_NAME }}
      REPO_PATH: ${{ steps.get-ocir-repository.outputs.repo_path }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set GITHUB_REF_NAME
        id: set-ref-name
        run: echo "GITHUB_REF_NAME=$(basename ${{ github.ref }})" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get or create an OCIR Repository
        uses: oracle-actions/get-ocir-repository@v1.2.1
        id: get-ocir-repository
        with:
          name: thehighlands
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}

      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.2.1
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "${{ steps.get-ocir-repository.outputs.repo_path }}:${{ github.sha }}"

  cd:
    needs: ci
    runs-on: ubuntu-22.04
    name: Deploy
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.3.2
        id: test-configure-kubectl-oke-action
        with:
          cluster: ${{ secrets.OCI_OKE_CLUSTER_OCID }}

      - name: Deploy
        env:
          GITHUB_REF_NAME: ${{ needs.ci.outputs.GITHUB_REF_NAME }}
          REPO_PATH: ${{ needs.ci.outputs.REPO_PATH }}
          SHA: ${{ github.sha }}
        run: |
          cd deployment/overlays/$GITHUB_REF_NAME

          kustomize edit set image webapp:latest=$REPO_PATH:$SHA

          git config --global user.name "@poly-glot-bot"
          git config --global user.email "poly-glot-bot@users.noreply.github.com"

          git commit -am "feat: Update deployment image tag to $SHA [skip ci]"
          git push

          kubectl apply -k .
